name: Initial pipeline

on:
  push:
    branches:
      - main

jobs:
  initial_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
  client_setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /./phonebook
    steps:
      - name: Install dependencies client
        run: npm ci
      - name: Build client
        run: npm run build
      - name: Run linting client
        run: npm run lint
